repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: '' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: '' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
